### ISSUE TITLE
Glioma classification based on 3D PET Images

### ISSUE THREAD

**Issue by Hogandr** [MrGiovanni/SuPreM#13]
Hello,
Can you give me some hints how to use your results for a task like "Glioma classification based on 3D PET Images"?
The reason is that I want to try Transfer learning since the dataset is relatively small and most architectures trained from scratch overfit.
Thanks in advance!

**Comment by MrGiovanni** [comment]
Hi @Hogandr 

You can take our pre-trained model, drop its decoder, append a layer of "global pooling" at the end of the encoder, and add 1 or 2 fully connected layer(s). It should be sufficient to perform fine-tuning on the "classification" task.

An example can be found at https://github.com/MrGiovanni/SuPreM/tree/main/target_applications

Thanks,
Zongwei

**Comment by MrGiovanni** [comment]
Here is another example of fine-tuning U-Net for classification tasks.
https://github.com/MrGiovanni/ModelsGenesis/tree/master/pytorch#3-fine-tune-models-genesis-on-your-own-target-task
