### ISSUE TITLE
Finetuning on dataset other than totalsegmentator

### ISSUE THREAD

**Issue by rajanish4** [MrGiovanni/SuPreM#14]
Hi,

Thanks for these models, I was wondering if you also have instructions for fine-tuning your models on other datasets (in-house or public). So far I only found instruction for totalsegmentator dataset. Please let me know if there is a way to do this on other datasets.

Thanks

**Comment by MrGiovanni** [comment]
Hi @rajanish4 

We've provided three examples of fine-tuning on other datasets at https://github.com/MrGiovanni/SuPreM/tree/main/target_applications

Please let us know if you have specific questions when fine-tuning our pre-trained models.

Best,
Zongwei

**Comment by rajanish4** [comment]
Hi @MrGiovanni, thanks, I have seen these, but my question is, what if I have a dataset that is not one of these, so do you have instructions for that? For instance, how to arrange them in folder and naming conventions and so on?

**Comment by MrGiovanni** [comment]
We arrange datasets as 

```
Name of Your Dataset
    ├── 1st CT ID
    │   ├── ct.nii.gz
    │   └── segmentations
    │       ├── aorta.nii.gz
    │       ├── gall_bladder.nii.gz
    │       ├── kidney_left.nii.gz
    │       ├── kidney_right.nii.gz
    │       ├── liver.nii.gz
    │       ├── pancreas.nii.gz
    │       ├── postcava.nii.gz
    │       ├── spleen.nii.gz
    │       ├── stomach.nii.gz
    │       └── ...
    ├── 2nd CT ID
    │   ├── ct.nii.gz
    │   └── segmentations
    │       ├── aorta.nii.gz
    │       ├── gall_bladder.nii.gz
    │       ├── kidney_left.nii.gz
    │       ├── kidney_right.nii.gz
    │       ├── liver.nii.gz
    │       ├── pancreas.nii.gz
    │       ├── postcava.nii.gz
    │       ├── spleen.nii.gz
    │       ├── stomach.nii.gz
    │       └── ...
    ├── 3rd CT ID
    │   ├── ct.nii.gz
    │   └── segmentations
    │       ├── aorta.nii.gz
    │       ├── gall_bladder.nii.gz
    │       ├── kidney_left.nii.gz
    │       ├── kidney_right.nii.gz
    │       ├── liver.nii.gz
    │       ├── pancreas.nii.gz
    │       ├── postcava.nii.gz
    │       ├── spleen.nii.gz
    │       ├── stomach.nii.gz
    │       └── ...
    ...
```

You should be able to run the fine-tuning code with minor modifications to the dataloader if the datasets are organized in this format.

Best,
Zongwei
